### ISSUE TITLE
Internet Explorer detect doesn't work to IE11

### ISSUE THREAD

**Issue by Richzendy** [emaxsaun/jwbox#2]
Hi again,

You use in your code this javascript function:

if (navigator.appName.indexOf("Microsoft") != -1)

To detect Internet Explorer browsers, but this function doesn't work anymore to Internet Explorer 11, maybe you could consider use this function instead:

function isIE() { return ((navigator.appName == 'Microsoft Internet Explorer') || ((navigator.appName == 'Netscape') && (new RegExp("Trident/.*rv:([0-9]{1,}[.0-9]{0,})").exec(navigator.userAgent) != null))); }

if (isIE) {
// do something
}

To reference, check: http://stackoverflow.com/questions/17907445/how-to-detect-ie11

**Comment by emaxsaun** [comment]
Hi,

Yes, I am not checking for IE11 in my code because the script works without
issue in IE11, so the code I am using works fine for my purpose / user
case, as I really only care about the older versions to fix a few issues.

Best,
-Ethan

On Wed, Jun 11, 2014 at 12:08 PM, Edwind Contreras <notifications@github.com
